[fingerprint]
blas_threads = 6
cpu_name = "alderlake"
julia_version = "1.12.1"
schema_version = 1
word_size = 64
cpu_threads = 12
os = "Linux"

[meta]
created_utc = "2026-03-09T22:58:11Z"
schema_version = 1

[thresholds]
rankqq_dim_small_threshold = 4096
qq_nemo_sparse_solve_threshold_square_low = 31
fp_nemo_nullspace_threshold = 1024
qq_nemo_sparse_solve_policy_square_low = -1
qq_nemo_sparse_solve_policy_wide_low = -1
zn_qq_dimat_submatrix_work_threshold = 32
qq_nemo_sparse_solve_threshold_wide_mid = 31
qq_nemo_sparse_solve_policy_tall_mid = 1
nemo_threshold = 392
qq_modular_nullspace_threshold_square = 256
modular_max_primes = 7
qq_nemo_sparse_solve_policy_square_mid = -1
qq_nemo_rank_threshold_square = 400
qq_nemo_sparse_solve_policy_tall_high = 1
qq_nemo_solve_threshold_wide = 12545
qq_nemo_sparse_solve_threshold_square_high = 31
fp_nemo_rank_threshold = 4096
qq_nemo_solve_threshold_tall = 18817
qq_nemo_nullspace_threshold_tall = 512
float_nullspace_svd_threshold = 180000
qq_modular_nullspace_threshold_wide = 512
rankqq_restricted_words_nemo_threshold = 16
qq_nemo_sparse_solve_threshold_tall_low = 47
qq_nemo_sparse_solve_policy_tall_low = -1
qq_nemo_sparse_solve_threshold_wide_high = 31
qq_nemo_sparse_solve_threshold_tall_mid = 119
fp_nemo_solve_threshold = 4608
qq_nemo_nullspace_threshold_square = 256
qq_nemo_sparse_solve_policy_wide_mid = -1
qq_nemo_rank_threshold_wide = 392
qq_nemo_nullspace_threshold_wide = 512
modular_nullspace_threshold = 512
qq_nemo_sparse_solve_threshold_square_mid = 31
qq_nemo_sparse_solve_policy_square_high = -1
qq_nemo_rank_threshold_tall = 392
qq_modular_solve_threshold_tall = 600
qq_modular_nullspace_threshold_tall = 512
qq_modular_solve_threshold_square = 400
qq_nemo_solve_threshold_square = 12545
qq_modular_solve_threshold_wide = 400
modular_solve_threshold = 400
qq_nemo_sparse_solve_threshold_wide_low = 31
qq_nemo_sparse_solve_policy_wide_high = -1
modular_min_primes = 1
qq_nemo_sparse_solve_threshold_tall_high = 266
