# APISurface.jl
#
# Canonical symbol contracts for the two curated public API tiers:
# - SIMPLE_API: default ergonomic surface for most users.
# - ADVANCED_API: strict superset for power users.
#
# This file is intentionally static and explicit. Do not auto-generate these
# lists from module exports.

const SIMPLE_API = (
    :QQ,
    :PointCloud, :ImageNd, :GraphData, :EmbeddedPlanarGraph2D,
    :GradedComplex, :MultiCriticalGradedComplex,
    :FiltrationSpec, :ConstructionBudget, :ConstructionOptions, :PipelineOptions, :DataFileOptions,
    :GradedFiltration,
    :RipsFiltration, :RipsDensityFiltration, :RipsCodensityFiltration, :RipsLowerStarFiltration, :FunctionRipsFiltration, :LandmarkRipsFiltration,
    :GraphLowerStarFiltration, :CliqueLowerStarFiltration, :EdgeWeightedFiltration,
    :GraphCentralityFiltration, :GraphGeodesicFiltration, :GraphFunctionGeodesicBifiltration,
    :GraphWeightThresholdFiltration,
    :ImageLowerStarFiltration, :ImageDistanceBifiltration, :WingVeinBifiltration,
    :DelaunayLowerStarFiltration, :AlphaFiltration, :FunctionDelaunayFiltration,
    :CoreDelaunayFiltration, :CoreFiltration, :DegreeRipsFiltration, :CubicalFiltration,
    :RhomboidFiltration,
    :filtration_kind, :filtration_arity, :build_graded_complex,
    :register_filtration_family!, :available_filtrations, :registered_filtration_families,
    :filtration_signature, :filtration_parameters, :construction_mode,
    :filtration_spec_summary, :filtration_family_summary,
    :point_codensity, :PointCodensityResult, :codensity_values, :codensity_mass, :neighbor_count,
    :encode, :coarsen, :common_refinement, :restriction, :pushforward_left, :pushforward_right, :derived_pushforward_left, :derived_pushforward_right,
    :resolve, :betti_table, :bass_table, :hom_dimension, :hom, :ext, :tor, :rhom, :derived_tensor, :hyperext, :hypertor, :ext_algebra, :invariant, :invariants,
    :rank_invariant, :rank_signed_measure, :restricted_hilbert, :point_signed_measure, :euler_surface, :euler_signed_measure,
    :rectangle_signed_barcode, :rectangle_signed_barcode_image,
    :slice_barcode, :slice_barcodes, :matching_distance, :matching_distance_exact_2d,
    :mp_landscape, :mpp_decomposition, :mpp_image,
    :mpp_decomposition_summary, :mpp_image_summary, :mp_landscape_summary,
    :visualize, :save_visual, :save_visuals, :available_visuals,
    :AbstractFeaturizerSpec,
    :PersistenceImageSpec, :LandscapeSpec, :MPLandscapeSpec, :EulerSurfaceSpec, :RankGridSpec,
    :RestrictedHilbertSpec,
    :BarcodeTopKSpec, :SlicedBarcodeSpec, :BarcodeSummarySpec,
    :PointSignedMeasureSpec, :EulerSignedMeasureSpec, :RectangleSignedBarcodeTopKSpec,
    :SignedBarcodeImageSpec, :ProjectedDistancesSpec, :MatchingDistanceBankSpec,
    :MPPImageSpec, :MPPDecompositionHistogramSpec,
    :BettiTableSpec, :BassTableSpec, :BettiSupportMeasuresSpec, :BassSupportMeasuresSpec, :CompositeSpec,
    :FeatureSet, :BatchOptions, :run_experiment, :load_experiment,
    :feature_names, :feature_axes, :nfeatures,
    :build_cache, :cache_stats,
    :transform, :transform!, :featurize, :batch_transform, :batch_transform!,
    :save_features, :load_features,
    :save_features_csv, :load_features_csv,
    :save_features_arrow, :load_features_arrow,
    :save_features_parquet, :load_features_parquet,
    :save_features_npz, :load_features_npz,
    :load_data, :inspect_data_file,
    :save_dataset_json, :load_dataset_json,
    :save_pipeline_json, :load_pipeline_json,
    :save_encoding_json, :load_encoding_json,
    :inspect_json,
    :SessionCache,
    :VisualExportResult,
    :export_path, :export_backend, :export_format, :export_kind, :export_stem,
    :EncodingResult, :EncodedComplexResult, :CohomologyDimsResult, :ModuleTranslationResult, :ResolutionResult, :InvariantResult, :unwrap,
    :result_summary,
    :encoding_poset, :encoding_module, :encoding_complex, :translated_module, :translation_map, :translation_kind, :encoding_map, :cohomology_dims,
    :encoding_axes, :encoding_representatives,
    :resolution_object, :invariant_value, :source_result,
    :dimensions, :describe,
    :CommonRefinementTranslationResult, :common_poset, :projection_maps, :translated_modules,
    :change_field,
    :one_criticalify, :criticality, :normalize_multicritical,
)

const SIMPLE_API_BINDINGS = (
    (:CoreModules, (
        :QQ,
        :SessionCache,
        :change_field,
    )),
    (:DataTypes, (
        :PointCloud, :ImageNd, :GraphData, :EmbeddedPlanarGraph2D,
        :GradedComplex, :MultiCriticalGradedComplex,
    )),
    (:Options, (
        :FiltrationSpec, :ConstructionBudget, :ConstructionOptions, :PipelineOptions, :DataFileOptions,
    )),
    (:Results, (
        :EncodingResult, :EncodedComplexResult, :CohomologyDimsResult, :ModuleTranslationResult, :ResolutionResult, :InvariantResult, :unwrap,
        :result_summary,
        :encoding_module, :encoding_complex, :translated_module, :translation_map, :translation_kind,
        :resolution_object, :invariant_value, :source_result,
    )),
    (:EncodingCore, (
        :encoding_poset, :encoding_map, :encoding_axes, :encoding_representatives,
    )),
    (:ChainComplexes, (
        :cohomology_dims, :dimensions, :describe,
    )),
    (:ChangeOfPosets, (
        :CommonRefinementTranslationResult, :common_poset, :projection_maps, :translated_modules,
    )),
    (:Workflow, (
        :encode, :coarsen, :common_refinement, :restriction, :pushforward_left, :pushforward_right, :derived_pushforward_left, :derived_pushforward_right,
        :resolve, :betti_table, :bass_table, :hom_dimension, :hom, :ext, :tor, :rhom, :derived_tensor, :hyperext, :hypertor, :ext_algebra, :invariant, :invariants,
        :rank_invariant, :rank_signed_measure, :restricted_hilbert, :point_signed_measure, :euler_surface, :euler_signed_measure,
        :rectangle_signed_barcode, :rectangle_signed_barcode_image,
        :slice_barcode, :slice_barcodes, :matching_distance_exact_2d,
        :mp_landscape, :mpp_decomposition, :mpp_image,
    )),
    (:MultiparameterImages, (
        :mpp_decomposition_summary, :mpp_image_summary, :mp_landscape_summary,
    )),
    (:Visualization, (
        :visualize, :save_visual, :save_visuals, :available_visuals,
        :VisualExportResult,
        :export_path, :export_backend, :export_format, :export_kind, :export_stem,
    )),
    (:DataIngestion, (
        :GradedFiltration,
        :RipsFiltration, :RipsDensityFiltration, :RipsCodensityFiltration, :RipsLowerStarFiltration, :FunctionRipsFiltration, :LandmarkRipsFiltration,
        :GraphLowerStarFiltration, :CliqueLowerStarFiltration, :EdgeWeightedFiltration,
        :GraphCentralityFiltration, :GraphGeodesicFiltration, :GraphFunctionGeodesicBifiltration,
        :GraphWeightThresholdFiltration,
        :ImageLowerStarFiltration, :ImageDistanceBifiltration, :WingVeinBifiltration,
        :DelaunayLowerStarFiltration, :AlphaFiltration, :FunctionDelaunayFiltration,
        :CoreDelaunayFiltration, :CoreFiltration, :DegreeRipsFiltration, :CubicalFiltration,
        :RhomboidFiltration,
        :filtration_kind, :filtration_arity, :build_graded_complex,
        :register_filtration_family!, :available_filtrations, :registered_filtration_families,
        :filtration_signature, :filtration_parameters, :construction_mode,
        :filtration_spec_summary, :filtration_family_summary,
        :point_codensity, :PointCodensityResult, :codensity_values, :codensity_mass, :neighbor_count,
        :one_criticalify, :criticality, :normalize_multicritical,
    )),
    (:DataFileIO, (
        :load_data, :inspect_data_file,
    )),
    (:Featurizers, (
        :matching_distance,
        :AbstractFeaturizerSpec,
        :PersistenceImageSpec, :LandscapeSpec, :MPLandscapeSpec, :EulerSurfaceSpec, :RankGridSpec,
        :RestrictedHilbertSpec,
        :BarcodeTopKSpec, :SlicedBarcodeSpec, :BarcodeSummarySpec,
        :PointSignedMeasureSpec, :EulerSignedMeasureSpec, :RectangleSignedBarcodeTopKSpec,
        :SignedBarcodeImageSpec, :ProjectedDistancesSpec, :MatchingDistanceBankSpec,
        :MPPImageSpec, :MPPDecompositionHistogramSpec,
        :BettiTableSpec, :BassTableSpec, :BettiSupportMeasuresSpec, :BassSupportMeasuresSpec, :CompositeSpec,
        :FeatureSet, :BatchOptions, :run_experiment, :load_experiment,
        :feature_names, :feature_axes, :nfeatures,
        :build_cache, :cache_stats,
        :transform, :transform!, :featurize, :batch_transform, :batch_transform!,
        :save_features, :load_features,
        :save_features_csv, :load_features_csv,
        :save_features_arrow, :load_features_arrow,
        :save_features_parquet, :load_features_parquet,
        :save_features_npz, :load_features_npz,
    )),
    (:Serialization, (
        :save_dataset_json, :load_dataset_json,
        :save_pipeline_json, :load_pipeline_json,
        :save_encoding_json, :load_encoding_json,
        :inspect_json,
    )),
)

const _ADVANCED_ONLY_API_RAW = (
    :PModule, :PMorphism, :ModuleOptions,
    :EncodingOptions, :ResolutionOptions, :InvariantOptions, :DerivedFunctorOptions,
    :FinitePoset, :ProductOfChainsPoset, :GridPoset, :ProductPoset,
    :Upset, :Downset, :FringeModule,
    :UpsetPresentation, :DownsetCopresentation,
    :check_poset, :check_upset, :check_downset, :check_fringe_data, :check_fringe_module,
    :check_upset_presentation, :check_downset_copresentation,
    :base_poset, :ambient_poset, :field, :birth_upsets, :death_downsets, :fringe_coefficients, :ngenerators, :nrelations,
    :generator_labels, :relation_labels, :cogenerator_labels, :corelation_labels,
    :presentation_matrix, :copresentation_matrix, :attached_fringe,
    :fringe_summary, :FiniteFringeValidationSummary, :finite_fringe_validation_summary,
    :principal_upset, :principal_downset,
    :upset_from_generators, :downset_from_generators,
    :one_by_one_fringe, :cover_edges,
    :nvertices, :leq, :leq_matrix,
    :pmodule_from_fringe, :projective_cover, :injective_hull,
    :upset_resolution, :downset_resolution, :indicator_resolutions,
    :verify_upset_resolution, :verify_downset_resolution,
    :ProjectiveCoverResult, :InjectiveHullResult,
    :UpsetResolutionResult, :DownsetResolutionResult, :IndicatorResolutionsResult,
    :IndicatorResolutionValidationSummary,
    :cover_module, :cover_map, :hull_module, :hull_map,
    :resolution_modules, :resolution_maps, :resolution_generators,
    :augmentation, :coaugmentation,
    :presentation_module, :presentation_map,
    :generator_vertices, :generator_blocks, :materialize_generators,
    :resolution_length, :generator_count, :generator_count_by_degree,
    :cover_summary, :hull_summary, :resolution_summary, :presentation_summary,
    :check_projective_cover, :check_injective_hull, :check_resolution, :check_fringe_presentation,
    :indicator_resolution_validation_summary,
    :EncodingMap, :UptightEncoding, :PostcomposedEncodingMap, :CompiledEncoding, :GridEncodingMap,
    :source_poset, :target_poset, :region_map, :constant_upsets,
    :compile_encoding, :locate, :locate_many, :locate_many!,
    :check_query_point, :check_query_matrix,
    :check_encoding_map, :check_compiled_encoding, :check_uptight_encoding, :check_postcomposed_encoding,
    :EncodingValidationSummary, :encoding_validation_summary, :encoding_summary,
    :check_region_geometry, :region_geometry_summary,
    :RegionGeometrySummary, :recommended_region_queries,
    :RegionGeometryValidationSummary, :region_geometry_validation_summary,
    :supported_region_queries, :supported_region_hooks, :supports_region_query,
    :check_region_query,
    :RegionPrincipalDirectionsSummary, :region_principal_directions_summary,
    :principal_values, :principal_vectors, :covariance_matrix,
    :available_quantities, :unavailable_quantities, :quantity_sources, :finite_box_used,
    :region_boundary,
    :fringe_presentation, :flange_presentation,
    :Face, :IndFlat, :IndInj, :Flange, :PLFringe, :BoxUpset, :BoxDownset, :PLEncodingMapBoxes,
    :check_face, :check_indflat, :check_indinj, :check_flange,
    :FlangeValidationSummary, :flange_validation_summary,
    :face, :flats, :injectives, :coefficient_matrix, :free_coordinates, :translation,
    :nflats, :ninjectives, :matrix_size, :generator_counts, :is_minimized, :active_counts,
    :check_flange_point, :check_flange_points, :flange_summary, :flange_query_summary,
    :lower_bounds, :upper_bounds,
    :axes_uniformity,
    :check_box_upset, :check_box_downset, :check_box_encoding_map,
    :check_box_point, :check_box_points, :check_box_region, :check_box_query_box,
    :PLBackendValidationSummary, :plbackend_validation_summary,
    :box_encoding_summary, :box_query_summary, :box_region_summary,
    :nupsets, :ndownsets, :check_pl_region, :pl_region_summary,
    :cohomology, :long_exact_sequence, :spectral_sequence,
    :filtered_cochain_complex,
    :CochainComplex, :CochainMap, :DoubleComplex, :DistinguishedTriangle,
    :LongExactSequence, :SpectralSequence, :FiltrationData, :ExtensionProblem,
    :check_complex, :check_bicomplex, :check_filtered_complex,
    :ChainComplexValidationSummary, :chain_complex_validation_summary,
    :source, :target, :differential, :component_labels,
    :a_range, :b_range, :block, :horizontal_differential, :vertical_differential,
    :filtration_steps, :filtration_dimensions, :filtration_dimension, :graded_piece,
    :extension_pieces, :splitting_matrix, :piece_range,
    :sequence_dimensions, :sequence_maps, :sequence_entry,
    :complex_summary, :bicomplex_summary, :spectral_sequence_summary,
    :filtration_summary, :extension_summary, :long_exact_sequence_summary,
    :representatives, :image_basis,
    :page_dims, :term_dims, :convergence_page, :nonzero_terms, :page_differentials,
    :filtration_dims, :filtration_basis, :filtration_subquotient,
    :split_total_cohomology, :filtration_data, :diagonal_criterion,
    :collapse_data, :extension_problem, :edge_inclusion, :edge_projection,
    :ModuleCochainComplex, :ModuleCochainMap, :ModuleCochainHomotopy, :ModuleDistinguishedTriangle,
    :mapping_cone, :mapping_cone_triangle, :cohomology_module, :cohomology_module_data,
    :induced_map_on_cohomology_modules, :is_quasi_isomorphism,
    :RHomComplex, :RHom, :HyperExtSpace, :hyperExt,
    :DerivedTensorComplex, :DerivedTensor, :HyperTorSpace, :hyperTor,
    :source_map, :target_map, :triangle_objects, :triangle_maps, :underlying_complex,
    :module_complex_summary, :module_map_summary, :module_homotopy_summary,
    :triangle_summary, :rhom_summary, :hyperext_summary, :derived_tensor_summary, :hypertor_summary,
    :check_module_complex, :check_module_complex_map, :check_module_homotopy,
    :check_module_triangle, :check_rhom_complex, :check_derived_tensor_complex,
    :ModuleComplexValidationSummary, :module_complex_validation_summary,
    :rhom_map_first, :rhom_map_second,
    :hyperExt_map_first, :hyperExt_map_second,
    :derived_tensor_map_first, :derived_tensor_map_second,
    :hyperTor_map_first, :hyperTor_map_second,
    :betti_table, :bass_table,
    :dim, :degree_range, :basis, :representative, :coordinates,
    :HomSpace, :ExtSpace, :ExtInjective, :TorSpace,
    :ext_map_first, :ext_map_second, :tor_map_first, :tor_map_second,
    :ExtLongExactSequenceFirst, :ExtLongExactSequenceSecond,
    :TorLongExactSequenceFirst, :TorLongExactSequenceSecond,
    :ExtDoubleComplex, :ExtSpectralSequence, :TorDoubleComplex, :TorSpectralSequence,
    :yoneda_product,
    :Rect, :RectSignedBarcode, :PointSignedMeasure, :SignedMeasureDecomposition,
    :RectValidationSummary, :RectSignedBarcodeValidationSummary,
    :PointSignedMeasureValidationSummary, :SignedMeasureDecompositionValidationSummary,
    :term, :largest_terms,
    :check_rect, :check_rect_signed_barcode, :check_point_signed_measure, :check_signed_measure_decomposition,
    :signed_measure_summary, :rect_signed_barcode_summary,
    :point_signed_measure_summary, :signed_measure_decomposition_summary,
    :RankInvariantResult, :SupportComponentsSummary,
    :nentries, :nonzero_pairs, :value_at, :store_zeros,
    :support_components, :ncomponents, :component_sizes, :components, :largest_component,
    :ModuleSizeSummary, :ModuleGeometrySummary, :ModuleGeometryAsymptoticsSummary,
    :SupportMeasureSummary, :SupportBoundingBox, :SupportGraphDiameterSummary,
    :BettiSupportMeasuresSummary, :BassSupportMeasuresSummary,
    :RankQueryValidationSummary, :SupportGeometryValidationSummary,
    :check_rank_query_points, :check_support_box, :check_support_window, :check_support_measure_query,
    :MPPLineSpec, :MPPDecomposition, :MPPImage, :MPLandscape,
    :MPPLineSpecValidationSummary, :MPPDecompositionValidationSummary, :MPPImageValidationSummary, :MPLandscapeValidationSummary,
    :line_direction, :line_offset, :line_basepoint, :line_omega,
    :nlines, :nsummands, :line_specs, :summand_segments, :summand_weights, :total_segments, :weight_sum,
    :decomposition, :ndirections, :noffsets, :landscape_slice,
    :mpp_line_spec_summary, :mpp_decomposition_summary, :mpp_image_summary, :mp_landscape_summary,
    :check_mpp_line_spec, :check_mpp_decomposition, :check_mpp_image, :check_mp_landscape,
    :VisualizationSpec, :AbstractVisualizationLayer,
    :VisualExportResult,
    :export_path, :export_backend, :export_format, :export_kind, :export_stem,
    :HeatmapLayer, :RectLayer, :SegmentLayer, :PolylineLayer, :PointLayer, :Point3Layer, :TextLayer, :Segment3Layer, :BarcodeLayer,
    :VisualizationValidationSummary,
    :visual_spec, :render, :check_visual_spec, :check_visual_request, :visual_summary,
    :visual_kind, :visual_layers, :visual_panels, :visual_axes, :visual_metadata,
    :slice_chain, :slice_chain_exact_2d, :matching_distance_exact_slices_2d, :SliceSpec, :collect_slices, :save_slices_json, :load_slices_json,
    :FiberedArrangement2D, :FiberedBarcodeCache2D, :FiberedSliceFamily2D, :FiberedSliceResult,
    :ProjectedArrangement1D, :ProjectedArrangement, :ProjectedBarcodeCache,
    :ProjectedBarcodesResult, :ProjectedDistancesResult,
    :source_encoding, :working_box, :direction_representatives, :slope_breaks,
    :ncells, :computed_cell_count, :chain_count, :backend, :shared_arrangement, :cached_barcode_count,
    :source_arrangement, :unique_chain_count, :direction_weight_scheme, :stores_values,
    :slice_direction, :slice_offset, :slice_offset_interval, :slice_chain_id, :slice_values,
    :projections, :nprojections, :projection_direction, :projection_values, :projection_chain,
    :projection_indices, :projection_directions, :computed_projection_count, :distance_metric,
    :Fibered2DValidationSummary, :fibered2d_validation_summary,
    :check_fibered_arrangement_2d, :check_fibered_barcode_cache_2d, :check_fibered_slice_family_2d,
    :check_projected_arrangement, :check_projected_barcode_cache,
    :check_fibered_cache_pair, :check_projected_cache_pair,
    :check_fibered_direction, :check_fibered_offset, :check_fibered_basepoint,
    :check_fibered_query, :check_projected_direction,
    :fibered_arrangement_summary, :fibered_cache_summary, :fibered_family_summary,
    :projected_arrangement_summary, :projected_cache_summary, :fibered_query_summary,
    :fibered_arrangement_2d, :fibered_barcode_cache_2d,
    :fibered_cell_id, :fibered_chain, :fibered_values, :fibered_barcode, :fibered_barcode_index,
    :fibered_slice, :fibered_barcode_cache_stats, :fibered_slice_family_2d,
    :matching_distance_exact_2d,
    :projected_arrangement, :projected_barcode_cache, :projected_barcodes,
    :projected_distances, :projected_distance, :projected_kernel,
    :direct_sum, :direct_sum_with_maps, :zero_pmodule, :zero_morphism,
    :dim_at, :component, :structure_map, :support, :nonzero_vertices, :support_dims,
    :MapLeqQueryBatch, :prepare_map_leq_batch,
    :map_leq, :map_leq_many, :map_leq_many!,
    :check_module, :check_morphism, :check_module_data, :check_morphism_data,
    :kernel, :cokernel, :image,
    :kernel_with_inclusion, :image_with_inclusion,
    :cokernel_with_projection, :coimage_with_projection,
    :Submodule, :submodule, :kernel_submodule, :image_submodule,
    :quotient, :quotient_with_projection, :coimage,
    :submodule_object, :ambient_module, :inclusion_map, :projection_map,
    :is_zero_morphism,
    :pushout, :pullback,
    :ShortExactSequence, :short_exact_sequence, :is_exact, :check_submodule, :check_short_exact_sequence,
    :SnakeLemmaResult, :snake_lemma, :connecting_map,
    :kernel_objects, :kernel_inclusions, :cokernel_objects, :cokernel_projections,
    :exactness_summary, :ValidationSummary, :validation_summary, :check_snake_lemma,
    :biproduct, :product, :coproduct, :equalizer, :coequalizer,
    :DiscretePairDiagram, :ParallelPairDiagram, :SpanDiagram, :CospanDiagram,
    :limit, :colimit,
    :ProductPosetResult, :CommonRefinementTranslationResult,
    :MonotoneMapValidationSummary, :CommonRefinementHomValidationSummary,
    :monotone_map_validation_summary, :common_refinement_hom_validation_summary,
    :common_poset, :projection_maps, :translated_modules,
    :CommonRefinementHomSpace, :CommonRefinementHomBasis,
    :basis_matrix, :common_refinement_summary,
    :check_common_refinement_hom, :check_monotone_map,
    :pushforward_left, :pushforward_right, :restriction, :product_poset, :encode_pmodules_to_common_poset,
    :hom_common_refinement, :hom_dim_common_refinement, :has_nonzero_hom_common_refinement, :hom_bidim_common_refinement,
    :left_kan_extension, :right_kan_extension, :derived_pushforward_left, :derived_pushforward_right,
    :projective_resolution, :injective_resolution,
    :Hom, :Ext, :Tor, :ExtAlgebra,
    :resolution_terms, :resolution_differentials,
    :augmentation_map, :coaugmentation_map,
    :source_module, :target_module,
    :nonzero_degrees, :degree_dimensions, :total_dimension,
    :page_dimensions,
    :generator_degrees, :algebra_field,
    :parent_algebra, :element_degree, :element_coordinates,
    :wrapped_spectral_sequence, :underlying_ext_space, :underlying_tor_space, :cached_product_degrees,
    :hom_summary, :ext_summary, :tor_summary,
    :double_complex_summary, :derived_les_summary, :algebra_summary,
    :DerivedFunctorValidationSummary, :derived_functor_validation_summary,
    :check_projective_resolution, :check_injective_resolution,
    :check_ext_spectral_sequence, :check_tor_spectral_sequence, :check_ext_algebra, :check_tor_algebra,
    :ExtElement, :TorElement,
    :parse_finite_fringe_json, :finite_fringe_from_m2,
    :save_flange_json, :load_flange_json, :parse_flange_json,
    :save_pl_fringe_json, :load_pl_fringe_json, :parse_pl_fringe_json,
    :JSONArtifactSummary, :SerializationValidationSummary,
    :artifact_kind, :schema_version, :artifact_field, :artifact_poset_kind,
    :artifact_path, :artifact_profile_hint, :artifact_data_kind,
    :has_encoding_map, :has_dense_leq, :artifact_size_bytes,
    :json_artifact_summary, :encoding_json_summary, :dataset_json_summary, :pipeline_json_summary,
    :flange_json_summary, :pl_fringe_json_summary, :mpp_decomposition_json_summary, :mpp_image_json_summary,
    :feature_metadata_summary,
    :serialization_validation_summary,
    :check_dataset_json, :check_pipeline_json, :check_encoding_json,
    :check_flange_json, :check_pl_fringe_json,
    :check_mpp_decomposition_json, :check_mpp_image_json,
    :check_feature_metadata_json,
    :check_json_save_profile, :check_encoding_save_profile, :check_include_leq_option,
    :check_serialization_validation_mode, :check_encoding_output_mode,
    :save_mpp_decomposition_json, :load_mpp_decomposition_json,
    :save_mpp_image_json, :load_mpp_image_json,
    :SyntheticFamily, :SyntheticBoxFringe,
    :noisy_annulus, :three_annuli, :coupled_orbit, :gaussian_clusters,
    :checkerboard_image, :planar_grid_graph,
    :chain_bar_fringe, :coupled_chain_fringe, :diamond_fringe,
    :box_bar_fringe, :staircase_box_fringe, :pl_box_fringe, :coupled_pl_fringe,
    :orthant_bar_flange, :mixed_face_flange,
    :synthetic_family, :sweep_family,
    :synthetic_items, :synthetic_parameters, :synthetic_labels, :synthetic_generator,
    :synthetic_family_summary, :box_fringe_summary,
    :check_synthetic_family, :check_synthetic_box_fringe,
    :npoints, :ambient_dim, :nedges, :max_dim, :cell_counts, :parameter_dim,
    :edge_list, :vertex_positions, :cell_grades, :boundary_maps, :simplex_grades,
    :vertex_coordinates, :edge_weights, :polylines, :bounding_box,
    :cells, :cell_grade, :boundary_map, :cell_grade_set,
    :nsimplices, :simplices, :simplex_dimension, :simplex_grade_set,
    :data_summary,
    :DataValidationSummary, :data_validation_summary,
    :check_point_cloud, :check_graph_data, :check_embedded_planar_graph,
    :check_graded_complex, :check_multicritical_complex, :check_simplex_tree_multi,
    :DataFileInspectionSummary, :DelimitedTableInspection, :DatasetFileInspection,
    :DataFileValidationSummary, :LoadDataValidationSummary, :TableColumnValidationSummary,
    :data_file_summary,
    :data_file_validation_summary, :load_data_validation_summary, :table_column_validation_summary,
    :check_data_file, :check_load_data, :check_table_columns,
    :ExperimentIOConfig, :ExperimentSpec, :ExperimentArtifact, :ExperimentResult,
    :LoadedExperimentArtifact, :LoadedExperimentResult,
    :FeaturizerSpecValidationSummary, :FeatureSetValidationSummary,
    :ExperimentSpecValidationSummary, :LoadedExperimentValidationSummary,
    :feature_set_summary, :experiment_summary, :experiment_artifact_summary, :featurizer_summary,
    :sample_ids, :feature_matrix, :feature_values, :sample_labels, :metadata,
    :experiment_name, :artifacts, :nartifacts, :artifact_keys, :artifact,
    :artifact_spec, :artifact_features, :artifact_elapsed_seconds,
    :feature_paths, :run_dir, :manifest_path, :total_elapsed_seconds, :has_features,
    :check_feature_set, :check_experiment_spec, :check_loaded_experiment, :check_featurizer_spec,
    :ResultValidationSummary, :result_validation_summary,
    :IngestionPlan, :IngestionEstimate, :GradedComplexBuildResult,
    :PointCodensityResult,
    :IngestionValidationSummary,
    :estimate_ingestion, :plan_ingestion, :run_ingestion,
    :point_codensity,
    :source_data, :plan_filtration, :plan_spec, :plan_construction, :plan_pipeline,
    :planned_stage, :plan_field, :has_preflight, :preflight_estimate, :route_hint,
    :multicritical_mode, :onecritical_selector, :enforce_boundary,
    :estimated_cells, :cell_counts_by_dim, :estimated_axis_sizes, :estimated_poset_size,
    :estimated_nnz, :estimated_dense_bytes, :estimate_warnings,
    :codensity_values, :codensity_mass, :neighbor_count,
    :graded_complex, :grade_axes, :grade_orientation,
    :check_filtration, :check_filtration_spec, :check_data_filtration, :check_ingestion_plan,
    :check_ingestion_estimate, :check_graded_complex_build_result,
    :check_ingestion_stage, :check_construction_options, :check_preflight_mode,
    :ingestion_validation_summary, :ingestion_plan_summary, :ingestion_estimate_summary,
    :graded_complex_build_summary,
    :check_encoding_result, :check_encoded_complex_result, :check_cohomology_dims_result, :check_resolution_result, :check_invariant_result,
)

const ADVANCED_ONLY_API = Tuple(sym for sym in _ADVANCED_ONLY_API_RAW if !(sym in SIMPLE_API))

const ADVANCED_ONLY_API_BINDINGS = (
    (:Modules, (
        :PModule, :PMorphism, :ModuleOptions,
        :direct_sum, :direct_sum_with_maps, :zero_pmodule, :zero_morphism,
        :dim_at, :component, :structure_map, :support, :nonzero_vertices, :support_dims,
        :MapLeqQueryBatch, :prepare_map_leq_batch,
        :map_leq, :map_leq_many, :map_leq_many!,
        :check_module, :check_morphism, :check_module_data, :check_morphism_data,
    )),
    (:Options, (
        :EncodingOptions, :ResolutionOptions, :InvariantOptions, :DerivedFunctorOptions,
    )),
    (:DataTypes, (
        :npoints, :ambient_dim, :nedges, :max_dim, :cell_counts, :parameter_dim,
        :edge_list, :vertex_positions, :cell_grades, :boundary_maps, :simplex_grades,
        :vertex_coordinates, :edge_weights, :polylines, :bounding_box,
        :cells, :cell_grade, :boundary_map, :cell_grade_set,
        :nsimplices, :simplices, :simplex_dimension, :simplex_grade_set,
        :data_summary,
        :DataValidationSummary, :data_validation_summary,
        :check_point_cloud, :check_graph_data, :check_embedded_planar_graph,
        :check_graded_complex, :check_multicritical_complex, :check_simplex_tree_multi,
    )),
    (:SyntheticData, (
        :SyntheticFamily, :SyntheticBoxFringe,
        :noisy_annulus, :three_annuli, :coupled_orbit, :gaussian_clusters,
        :checkerboard_image, :planar_grid_graph,
        :chain_bar_fringe, :coupled_chain_fringe, :diamond_fringe,
        :box_bar_fringe, :staircase_box_fringe, :pl_box_fringe, :coupled_pl_fringe,
        :orthant_bar_flange, :mixed_face_flange,
        :synthetic_family, :sweep_family,
        :synthetic_items, :synthetic_parameters, :synthetic_labels, :synthetic_generator,
        :synthetic_family_summary, :box_fringe_summary,
        :check_synthetic_family, :check_synthetic_box_fringe,
    )),
    (:DataFileIO, (
        :DataFileInspectionSummary, :DelimitedTableInspection, :DatasetFileInspection,
        :DataFileValidationSummary, :LoadDataValidationSummary, :TableColumnValidationSummary,
        :data_file_summary,
        :data_file_validation_summary, :load_data_validation_summary, :table_column_validation_summary,
        :check_data_file, :check_load_data, :check_table_columns,
    )),
    (:Featurizers, (
        :ExperimentIOConfig, :ExperimentSpec, :ExperimentArtifact, :ExperimentResult,
        :LoadedExperimentArtifact, :LoadedExperimentResult,
        :FeaturizerSpecValidationSummary, :FeatureSetValidationSummary,
        :ExperimentSpecValidationSummary, :LoadedExperimentValidationSummary,
        :feature_set_summary, :experiment_summary, :experiment_artifact_summary, :featurizer_summary,
        :sample_ids, :feature_matrix, :feature_values, :sample_labels, :metadata,
        :experiment_name, :artifacts, :nartifacts, :artifact_keys, :artifact,
        :artifact_spec, :artifact_features, :artifact_elapsed_seconds,
        :feature_paths, :run_dir, :manifest_path, :total_elapsed_seconds, :has_features,
        :check_feature_set, :check_experiment_spec, :check_loaded_experiment, :check_featurizer_spec,
    )),
    (:Results, (
        :ResultValidationSummary, :result_validation_summary,
        :check_encoding_result, :check_encoded_complex_result, :check_cohomology_dims_result, :check_resolution_result, :check_invariant_result,
    )),
    (:ModuleComplexes, (
        :ModuleCochainComplex, :ModuleCochainMap, :ModuleCochainHomotopy, :ModuleDistinguishedTriangle,
        :mapping_cone, :mapping_cone_triangle, :cohomology_module, :cohomology_module_data,
        :induced_map_on_cohomology_modules, :is_quasi_isomorphism,
        :RHomComplex, :RHom, :HyperExtSpace, :hyperExt,
        :DerivedTensorComplex, :DerivedTensor, :HyperTorSpace, :hyperTor,
        :source_map, :target_map, :triangle_objects, :triangle_maps, :underlying_complex,
        :module_complex_summary, :module_map_summary, :module_homotopy_summary,
        :triangle_summary, :rhom_summary, :hyperext_summary, :derived_tensor_summary, :hypertor_summary,
        :check_module_complex, :check_module_complex_map, :check_module_homotopy,
        :check_module_triangle, :check_rhom_complex, :check_derived_tensor_complex,
        :ModuleComplexValidationSummary, :module_complex_validation_summary,
        :rhom_map_first, :rhom_map_second,
        :hyperExt_map_first, :hyperExt_map_second,
        :derived_tensor_map_first, :derived_tensor_map_second,
        :hyperTor_map_first, :hyperTor_map_second,
    )),
    (:ChainComplexes, (
        :cohomology, :long_exact_sequence, :spectral_sequence,
        :filtered_cochain_complex,
        :CochainComplex, :CochainMap, :DoubleComplex, :DistinguishedTriangle,
        :LongExactSequence, :SpectralSequence, :FiltrationData, :ExtensionProblem,
        :check_complex, :check_bicomplex, :check_filtered_complex,
        :ChainComplexValidationSummary, :chain_complex_validation_summary,
        :source, :target, :differential, :component_labels,
        :a_range, :b_range, :block, :horizontal_differential, :vertical_differential,
        :filtration_steps, :filtration_dimensions, :filtration_dimension, :graded_piece,
        :extension_pieces, :splitting_matrix, :piece_range,
        :sequence_dimensions, :sequence_maps, :sequence_entry,
        :complex_summary, :bicomplex_summary, :spectral_sequence_summary,
        :filtration_summary, :extension_summary, :long_exact_sequence_summary,
        :representatives, :image_basis,
        :page_dims, :term_dims, :convergence_page, :nonzero_terms, :page_differentials,
        :filtration_dims, :filtration_basis, :filtration_subquotient,
        :split_total_cohomology, :filtration_data, :diagonal_criterion,
        :collapse_data, :extension_problem, :edge_inclusion, :edge_projection,
    )),
    (:FiniteFringe, (
        :FinitePoset, :ProductOfChainsPoset, :GridPoset, :ProductPoset,
        :Upset, :Downset, :FringeModule,
        :check_poset, :check_upset, :check_downset, :check_fringe_data, :check_fringe_module,
        :base_poset, :ambient_poset, :field, :birth_upsets, :death_downsets, :fringe_coefficients, :ngenerators, :nrelations,
        :fringe_summary, :FiniteFringeValidationSummary, :finite_fringe_validation_summary,
        :principal_upset, :principal_downset,
        :upset_from_generators, :downset_from_generators,
        :one_by_one_fringe, :cover_edges,
        :nvertices, :leq, :leq_matrix,
    )),
    (:Encoding, (
        :EncodingMap, :UptightEncoding, :PostcomposedEncodingMap,
        :source_poset, :target_poset, :region_map, :constant_upsets,
        :check_uptight_encoding, :check_postcomposed_encoding,
    )),
    (:IndicatorTypes, (
        :UpsetPresentation, :DownsetCopresentation,
        :check_upset_presentation, :check_downset_copresentation,
        :generator_labels, :relation_labels, :cogenerator_labels, :corelation_labels,
        :presentation_matrix, :copresentation_matrix, :attached_fringe,
    )),
    (:EncodingCore, (
        :CompiledEncoding, :GridEncodingMap,
        :compile_encoding, :locate, :locate_many, :locate_many!,
        :check_query_point, :check_query_matrix,
        :check_encoding_map, :check_compiled_encoding,
        :EncodingValidationSummary, :encoding_validation_summary, :encoding_summary,
    )),
    (:Visualization, (
        :VisualizationSpec, :AbstractVisualizationLayer,
        :VisualExportResult,
        :export_path, :export_backend, :export_format, :export_kind, :export_stem,
        :HeatmapLayer, :RectLayer, :SegmentLayer, :PolylineLayer, :PointLayer, :Point3Layer, :TextLayer, :Segment3Layer, :BarcodeLayer,
        :VisualizationValidationSummary,
        :visual_spec, :render, :check_visual_spec, :check_visual_request, :visual_summary,
        :visual_kind, :visual_layers, :visual_panels, :visual_axes, :visual_metadata,
    )),
    (:ZnEncoding, (
        :ZnEncodingMap, :SignaturePoset, :ZnEncodingCache,
        :compile_zn_cache,
        :region_poset, :nregions, :critical_coordinates, :critical_coordinate_counts,
        :region_representatives, :region_representative, :region_signature, :zn_region_summary,
        :flats, :injectives, :generator_counts, :cell_shape, :has_direct_lookup, :poset_kind,
        :zn_encoding_summary, :zn_query_summary,
        :check_zn_box,
        :check_zn_encoding_map, :check_signature_poset, :check_zn_cache,
        :check_zn_query_point, :check_zn_query_matrix,
        :ZnEncodingValidationSummary, :zn_encoding_validation_summary,
    )),
    (:RegionGeometry, (
        :check_region_geometry, :region_geometry_summary,
        :RegionGeometrySummary, :recommended_region_queries,
        :RegionGeometryValidationSummary, :region_geometry_validation_summary,
        :supported_region_queries, :supported_region_hooks, :supports_region_query,
        :check_region_query,
        :RegionPrincipalDirectionsSummary, :region_principal_directions_summary,
        :principal_values, :principal_vectors, :covariance_matrix,
        :available_quantities, :unavailable_quantities, :quantity_sources, :finite_box_used,
        :region_boundary,
    )),
    (:Workflow, (
        :fringe_presentation, :flange_presentation,
    )),
    (:FlangeZn, (
        :Face, :IndFlat, :IndInj, :Flange,
        :check_face, :check_indflat, :check_indinj, :check_flange,
        :FlangeValidationSummary, :flange_validation_summary,
        :face, :flats, :injectives, :coefficient_matrix, :free_coordinates, :translation,
        :nflats, :ninjectives, :matrix_size, :generator_counts, :is_minimized, :active_counts,
        :check_flange_point, :check_flange_points, :flange_summary, :flange_query_summary,
    )),
    (:PLPolyhedra, (
        :HPoly, :PolyUnion, :PLUpset, :PLDownset, :PLFringe, :PLEncodingMap, :PolyInBoxCache,
        :make_hpoly, :poly_union, :encode_from_PL_fringe, :encode_from_PL_fringes,
        :poly_in_box_cache, :compile_geometry_cache, :contains,
        :polyhedra, :npolyhedra,
        :nupsets, :ndownsets,
        :birth_upsets, :death_downsets, :coefficient_matrix,
        :nregions, :region_witnesses, :region_witness, :region_signature,
        :has_spatial_index, :cache_box, :cache_level, :cached_region_count,
        :check_hpoly, :check_poly_union, :check_pl_upset, :check_pl_downset,
        :check_pl_fringe, :check_pl_encoding_map, :check_poly_in_box_cache,
        :check_pl_point, :check_pl_points, :check_pl_box, :check_pl_region,
        :PLPolyhedraValidationSummary, :plpolyhedra_validation_summary,
        :pl_fringe_summary, :pl_encoding_summary, :pl_query_summary, :pl_region_summary, :poly_cache_summary,
    )),
    (:PLBackend, (
        :BoxUpset, :BoxDownset, :PLEncodingMapBoxes,
        :lower_bounds, :upper_bounds, :axes_uniformity,
        :check_box_upset, :check_box_downset, :check_box_encoding_map,
        :check_box_point, :check_box_points, :check_box_region, :check_box_query_box,
        :PLBackendValidationSummary, :plbackend_validation_summary,
        :box_encoding_summary, :box_query_summary, :box_region_summary,
    )),
    (:DerivedFunctors, (
        :betti_table, :bass_table,
        :dim, :degree_range, :basis, :representative, :coordinates,
        :resolution_terms, :resolution_differentials,
        :augmentation_map, :coaugmentation_map,
        :source_module, :target_module,
        :nonzero_degrees, :degree_dimensions, :total_dimension,
        :page_dimensions,
        :generator_degrees, :algebra_field,
        :parent_algebra, :element_degree, :element_coordinates,
        :wrapped_spectral_sequence, :underlying_ext_space, :underlying_tor_space, :cached_product_degrees,
        :hom_summary, :ext_summary, :tor_summary,
        :double_complex_summary, :derived_les_summary, :algebra_summary,
        :DerivedFunctorValidationSummary, :derived_functor_validation_summary,
        :check_projective_resolution, :check_injective_resolution,
        :check_ext_spectral_sequence, :check_tor_spectral_sequence, :check_ext_algebra, :check_tor_algebra,
        :ProjectiveResolution, :InjectiveResolution,
        :HomSpace, :ExtSpaceProjective, :ExtSpaceInjective, :ExtSpace, :ExtInjective, :TorSpace, :TorSpaceSecond,
        :ExtAlgebra, :TorAlgebra, :ExtElement, :TorElement,
        :ext_map_first, :ext_map_second, :tor_map_first, :tor_map_second,
        :ExtLongExactSequenceFirst, :ExtLongExactSequenceSecond,
        :TorLongExactSequenceFirst, :TorLongExactSequenceSecond,
        :ExtDoubleComplex, :ExtSpectralSequence, :TorDoubleComplex, :TorSpectralSequence,
        :yoneda_product,
        :projective_resolution, :injective_resolution,
        :Hom, :Ext, :Tor, :ExtAlgebra,
    )),
    (:IndicatorResolutions, (
        :pmodule_from_fringe, :projective_cover, :injective_hull,
        :upset_resolution, :downset_resolution, :indicator_resolutions,
        :verify_upset_resolution, :verify_downset_resolution,
        :ProjectiveCoverResult, :InjectiveHullResult,
        :UpsetResolutionResult, :DownsetResolutionResult, :IndicatorResolutionsResult,
        :IndicatorResolutionValidationSummary,
        :cover_module, :cover_map, :hull_module, :hull_map,
        :resolution_modules, :resolution_maps, :resolution_generators,
        :augmentation, :coaugmentation,
        :presentation_module, :presentation_map,
        :generator_vertices, :generator_blocks, :materialize_generators,
        :resolution_length, :generator_count, :generator_count_by_degree,
        :cover_summary, :hull_summary, :resolution_summary, :presentation_summary,
        :check_projective_cover, :check_injective_hull, :check_resolution, :check_fringe_presentation,
        :indicator_resolution_validation_summary,
    )),
    (:DataIngestion, (
        :IngestionPlan, :IngestionEstimate, :GradedComplexBuildResult,
        :PointCodensityResult,
        :IngestionValidationSummary,
        :estimate_ingestion, :plan_ingestion, :run_ingestion,
        :point_codensity,
        :source_data, :plan_filtration, :plan_spec, :plan_construction, :plan_pipeline,
        :planned_stage, :plan_field, :has_preflight, :preflight_estimate, :route_hint,
        :multicritical_mode, :onecritical_selector, :enforce_boundary,
        :estimated_cells, :cell_counts_by_dim, :estimated_axis_sizes, :estimated_poset_size,
        :estimated_nnz, :estimated_dense_bytes, :estimate_warnings,
        :codensity_values, :codensity_mass, :neighbor_count,
        :graded_complex, :grade_axes, :grade_orientation,
        :check_filtration, :check_filtration_spec, :check_data_filtration, :check_ingestion_plan,
        :check_ingestion_estimate, :check_graded_complex_build_result,
        :check_ingestion_stage, :check_construction_options, :check_preflight_mode,
        :ingestion_validation_summary, :ingestion_plan_summary, :ingestion_estimate_summary,
        :graded_complex_build_summary,
    )),
    (:SignedMeasures, (
        :Rect, :RectSignedBarcode, :PointSignedMeasure, :SignedMeasureDecomposition,
        :RectValidationSummary, :RectSignedBarcodeValidationSummary,
        :PointSignedMeasureValidationSummary, :SignedMeasureDecompositionValidationSummary,
        :term, :largest_terms,
        :check_rect, :check_rect_signed_barcode, :check_point_signed_measure, :check_signed_measure_decomposition,
        :signed_measure_summary, :rect_signed_barcode_summary,
        :point_signed_measure_summary, :signed_measure_decomposition_summary,
    )),
    (:SliceInvariants, (
        :PersistenceLandscape1D, :PersistenceImage1D, :SliceBarcodesResult, :SliceFeaturesResult,
        :CompiledSlicePlan, :SlicePlanCache, :SliceModuleCache, :SliceModulePairCache,
        :SliceBarcodesTask, :SliceDistanceTask, :SliceKernelTask,
        :SliceInvariantValidationSummary, :slice_invariant_validation_summary,
        :compile_slice_plan, :compile_slices, :run_invariants, :module_cache,
        :slice_chain, :collect_slices, :save_slices_json, :load_slices_json,
        :slice_features, :slice_kernel,
        :landscape_grid, :landscape_values, :landscape_layers, :feature_dimension,
        :image_xgrid, :image_ygrid, :image_values, :image_shape,
        :slice_weights, :slice_directions, :slice_offsets, :packed_barcodes,
        :feature_kind, :feature_aggregate,
        :plan_directions, :plan_offsets, :plan_weights, :nslices, :total_weight,
        :slice_spec, :plan_has_values, :plan_value_mode,
        :left_cache, :right_cache, :cached_barcode_plan_count, :cached_landscape_plan_count,
        :task_kind, :task_threads, :distance_function, :kernel_kind, :kernel_sigma,
        :check_persistence_landscape, :check_persistence_image,
        :check_compiled_slice_plan, :check_slice_plan_cache,
        :check_slice_module_cache, :check_slice_module_pair_cache,
        :check_slice_barcodes_task, :check_slice_distance_task, :check_slice_kernel_task,
        :check_slice_direction, :check_slice_basepoint, :check_slice_request, :check_slice_specs,
        :landscape_summary, :persistence_image_summary, :slice_plan_summary,
        :slice_cache_summary, :slice_pair_cache_summary, :slice_task_summary, :slice_collection_summary,
    )),
    (:Invariants, (
        :RankInvariantResult, :SupportComponentsSummary,
        :nentries, :nonzero_pairs, :value_at, :store_zeros,
        :support_components, :ncomponents, :component_sizes, :components, :largest_component,
        :ModuleSizeSummary, :ModuleGeometrySummary, :ModuleGeometryAsymptoticsSummary,
        :SupportMeasureSummary, :SupportBoundingBox, :SupportGraphDiameterSummary,
        :BettiSupportMeasuresSummary, :BassSupportMeasuresSummary,
        :RankQueryValidationSummary, :SupportGeometryValidationSummary,
        :check_rank_query_points, :check_support_box, :check_support_window, :check_support_measure_query,
    )),
    (:MultiparameterImages, (
        :MPPLineSpec, :MPPDecomposition, :MPPImage, :MPLandscape,
        :MPPLineSpecValidationSummary, :MPPDecompositionValidationSummary, :MPPImageValidationSummary, :MPLandscapeValidationSummary,
        :line_direction, :line_offset, :line_basepoint, :line_omega,
        :nlines, :nsummands, :line_specs, :summand_segments, :summand_weights, :total_segments, :weight_sum,
        :decomposition, :ndirections, :noffsets, :landscape_slice,
        :mpp_line_spec_summary, :mpp_decomposition_summary, :mpp_image_summary, :mp_landscape_summary,
        :check_mpp_line_spec, :check_mpp_decomposition, :check_mpp_image, :check_mp_landscape,
    )),
    (:Fibered2D, (
        :slice_chain_exact_2d, :matching_distance_exact_slices_2d,
        :FiberedArrangement2D, :FiberedBarcodeCache2D, :FiberedSliceFamily2D, :FiberedSliceResult,
        :ProjectedArrangement1D, :ProjectedArrangement, :ProjectedBarcodeCache,
        :ProjectedBarcodesResult, :ProjectedDistancesResult,
        :source_encoding, :working_box, :direction_representatives, :slope_breaks,
        :ncells, :computed_cell_count, :chain_count, :backend, :shared_arrangement, :cached_barcode_count,
        :source_arrangement, :unique_chain_count, :direction_weight_scheme, :stores_values,
        :slice_direction, :slice_offset, :slice_offset_interval, :slice_chain_id, :slice_values,
        :projections, :nprojections, :projection_direction, :projection_values, :projection_chain,
        :projection_indices, :projection_directions, :computed_projection_count, :distance_metric,
        :Fibered2DValidationSummary, :fibered2d_validation_summary,
        :check_fibered_arrangement_2d, :check_fibered_barcode_cache_2d, :check_fibered_slice_family_2d,
        :check_projected_arrangement, :check_projected_barcode_cache,
        :check_fibered_cache_pair, :check_projected_cache_pair,
        :check_fibered_direction, :check_fibered_offset, :check_fibered_basepoint,
        :check_fibered_query, :check_projected_direction,
        :fibered_arrangement_summary, :fibered_cache_summary, :fibered_family_summary,
        :projected_arrangement_summary, :projected_cache_summary, :fibered_query_summary,
        :fibered_arrangement_2d, :fibered_barcode_cache_2d,
        :fibered_cell_id, :fibered_chain, :fibered_values, :fibered_barcode, :fibered_barcode_index,
        :fibered_slice, :fibered_barcode_cache_stats, :fibered_slice_family_2d,
        :matching_distance_exact_2d,
        :projected_arrangement, :projected_barcode_cache, :projected_barcodes,
        :projected_distances, :projected_distance, :projected_kernel,
    )),
    (:InvariantCore, (
        :SliceSpec,
    )),
    (:AbelianCategories, (
        :kernel, :cokernel, :image,
        :kernel_with_inclusion, :image_with_inclusion,
        :cokernel_with_projection, :coimage_with_projection,
        :Submodule, :submodule, :kernel_submodule, :image_submodule,
        :quotient, :quotient_with_projection, :coimage,
        :submodule_object, :ambient_module, :inclusion_map, :projection_map,
        :is_zero_morphism,
        :pushout, :pullback,
        :ShortExactSequence, :short_exact_sequence, :is_exact, :check_submodule, :check_short_exact_sequence,
        :SnakeLemmaResult, :snake_lemma, :connecting_map,
        :kernel_objects, :kernel_inclusions, :cokernel_objects, :cokernel_projections,
        :exactness_summary, :ValidationSummary, :validation_summary, :check_snake_lemma,
        :biproduct, :product, :coproduct, :equalizer, :coequalizer,
        :DiscretePairDiagram, :ParallelPairDiagram, :SpanDiagram, :CospanDiagram,
        :limit, :colimit,
    )),
    (:ChangeOfPosets, (
        :ProductPosetResult, :CommonRefinementTranslationResult,
        :MonotoneMapValidationSummary, :CommonRefinementHomValidationSummary,
        :monotone_map_validation_summary, :common_refinement_hom_validation_summary,
        :common_poset, :projection_maps, :translated_modules,
        :CommonRefinementHomSpace, :CommonRefinementHomBasis,
        :basis_matrix, :common_refinement_summary,
        :check_common_refinement_hom, :check_monotone_map,
        :pushforward_left, :pushforward_right, :restriction, :product_poset, :encode_pmodules_to_common_poset,
        :hom_common_refinement, :hom_dim_common_refinement, :has_nonzero_hom_common_refinement, :hom_bidim_common_refinement,
        :left_kan_extension, :right_kan_extension, :derived_pushforward_left, :derived_pushforward_right,
    )),
    (:Serialization, (
        :parse_finite_fringe_json, :finite_fringe_from_m2,
        :save_flange_json, :load_flange_json, :parse_flange_json,
        :save_pl_fringe_json, :load_pl_fringe_json, :parse_pl_fringe_json,
        :JSONArtifactSummary, :SerializationValidationSummary,
        :artifact_kind, :schema_version, :artifact_field, :artifact_poset_kind,
        :artifact_path, :artifact_profile_hint, :artifact_data_kind,
        :has_encoding_map, :has_dense_leq, :artifact_size_bytes,
        :json_artifact_summary, :encoding_json_summary, :dataset_json_summary, :pipeline_json_summary,
        :flange_json_summary, :pl_fringe_json_summary, :mpp_decomposition_json_summary, :mpp_image_json_summary,
        :feature_metadata_summary,
        :serialization_validation_summary,
        :check_dataset_json, :check_pipeline_json, :check_encoding_json,
        :check_flange_json, :check_pl_fringe_json,
        :check_mpp_decomposition_json, :check_mpp_image_json,
        :check_feature_metadata_json,
        :check_json_save_profile, :check_encoding_save_profile, :check_include_leq_option,
        :check_serialization_validation_mode, :check_encoding_output_mode,
        :save_mpp_decomposition_json, :load_mpp_decomposition_json,
        :save_mpp_image_json, :load_mpp_image_json,
    )),
)

const ADVANCED_API = (SIMPLE_API..., ADVANCED_ONLY_API...)

function _bind_api_symbol!(target::Module, source::Module, sym::Symbol)
    isdefined(target, sym) && return
    isdefined(source, sym) || error("API surface mismatch: $(source).$(sym) is not defined.")
    Core.eval(target, :(const $(sym) = getfield($(source), $(QuoteNode(sym)))))
    Core.eval(target, :(export $(sym)))
    return
end

function _bind_api_list!(target::Module, source::Module, syms)
    for sym in syms
        _bind_api_symbol!(target, source, sym)
    end
    return
end

function _bind_api_bindings!(target::Module, bindings)
    for (modsym, syms) in bindings
        isdefined(target, modsym) || error("API surface mismatch: module $(target).$(modsym) is not defined.")
        source = getfield(target, modsym)
        source isa Module || error("API surface mismatch: $(target).$(modsym) is not a module.")
        _bind_api_list!(target, source, syms)
    end
    return
end

function _assert_api_list_defined!(target::Module, syms; label::AbstractString="API")
    for sym in syms
        isdefined(target, sym) || error("$(label) mismatch: $(target).$(sym) is not defined.")
    end
    return
end

function _export_api_symbol!(target::Module, sym::Symbol)
    isdefined(target, sym) || error("Export contract mismatch: $(target).$(sym) is not defined.")
    Core.eval(target, :(export $(sym)))
    return
end

function _export_api_list!(target::Module, syms)
    for sym in syms
        _export_api_symbol!(target, sym)
    end
    return
end
