[fingerprint]
blas_threads = 6
cpu_name = "alderlake"
julia_version = "1.12.1"
schema_version = 1
word_size = 64
cpu_threads = 12
os = "Linux"

[meta]
created_utc = "2026-03-08T04:19:50Z"
schema_version = 1

[thresholds]
rankqq_dim_small_threshold = 20000
qq_nemo_sparse_solve_threshold_square_low = 40
fp_nemo_nullspace_threshold = 1024
qq_nemo_sparse_solve_policy_square_low = 1
qq_nemo_sparse_solve_policy_wide_low = 1
zn_qq_dimat_submatrix_work_threshold = 48
qq_nemo_sparse_solve_threshold_wide_mid = 40
qq_nemo_sparse_solve_policy_tall_mid = 1
nemo_threshold = 512
qq_modular_nullspace_threshold_square = 400
modular_max_primes = 6
qq_nemo_sparse_solve_policy_square_mid = 1
qq_nemo_rank_threshold_square = 576
qq_nemo_sparse_solve_policy_tall_high = 1
qq_nemo_solve_threshold_wide = 576
qq_nemo_sparse_solve_threshold_square_high = 40
fp_nemo_rank_threshold = 4096
qq_nemo_solve_threshold_tall = 864
qq_nemo_nullspace_threshold_tall = 800
float_nullspace_svd_threshold = 180000
qq_modular_nullspace_threshold_wide = 800
qq_nemo_sparse_solve_threshold_tall_low = 76
qq_nemo_sparse_solve_policy_tall_low = 1
qq_nemo_sparse_solve_threshold_wide_high = 40
qq_nemo_sparse_solve_threshold_tall_mid = 209
fp_nemo_solve_threshold = 6144
qq_nemo_nullspace_threshold_square = 400
qq_nemo_sparse_solve_policy_wide_mid = 1
qq_nemo_rank_threshold_wide = 512
float_sparse_svds_min_dim = 1024
qq_nemo_nullspace_threshold_wide = 800
modular_nullspace_threshold = 800
qq_nemo_sparse_solve_threshold_square_mid = 40
qq_nemo_sparse_solve_policy_square_high = 1
qq_nemo_rank_threshold_tall = 512
qq_modular_solve_threshold_tall = 864
qq_modular_nullspace_threshold_tall = 800
qq_modular_solve_threshold_square = 576
qq_nemo_solve_threshold_square = 576
qq_modular_solve_threshold_wide = 576
float_sparse_svds_min_nnz = 120000
modular_solve_threshold = 576
qq_nemo_sparse_solve_threshold_wide_low = 40
qq_nemo_sparse_solve_policy_wide_high = 1
modular_min_primes = 2
qq_nemo_sparse_solve_threshold_tall_high = 405
